version: "3"

vars:
  PORT: 3002

  VENV_DIR: .venv
  DOCKER_RUNTIME: "docker exec {{.container_name}}"
  PYTHON_BIN: "{{ .DOCKER_RUNTIME }} {{ .VENV_DIR }}/bin/python3"
  PIP_BIN: "{{ .DOCKER_RUNTIME }} {{ .VENV_DIR }}/bin/pip3"
  YARN_BIN: "{{ .DOCKER_RUNTIME }} yarn"

dotenv: [".env", ".env.local"]

tasks:
  compose-up:
    preconditions:
      - which docker
    cmds:
      - docker compose up -d

  compose-down:
    cmds:
      - docker compose down

  venv:
    desc: "Setup python virtual environment"
    status:
      - which python3
    cmds:
      - python3 -m venv .venv

  install-python:
    desc: "Install python packages"
    deps:
      - venv
    sources:
      - requirements.txt
    generates:
      - "{{ .VENV_DIR }}/*"
    cmds:
      - "{{ .PIP_BIN }} install -r requirements.txt"

  install-yarn:
    desc: "Install yarn packages"
    status:
      - which yarn
      - which node
    sources:
      - yarn.lock
      - package.json
    generates:
      - "node_modules/**"
    cmds:
      - yarn install

  start:
    ignore_error: true
    deps:
      - install-python
      - install-yarn
      - compose-up
    cmds:
      - yarn start
      - defer: { task: compose-down }

  clean:
    cmds:
      - rm -rf static/css node_modules {{ .VENV_DIR }} .task
