name: PR Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Taskfile
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: task lint

      - name: Test
        run: task test

      - name: Start server
        run: task start &

      - name: Check server is running
        run: |
          echo "PORT=$(task -s get-port)" >> $GITHUB_ENV
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:$PORT
