name: PR Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint task
        run: task lint

      - name: Run test task
        run: task test

      - name: Run start task
        run: task start &

      - name: Get port from Taskfile
        run: echo "PORT=$(task -s get-port)" >> $GITHUB_ENV

      - name: Check if server is running
        run: curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:${{ env.PORT }}

      - name: Stop server
        run: task compose-down
